//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxOverflow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerTBL
    {
        public AnswerTBL()
        {
            this.AnswerCommentTBLs = new HashSet<AnswerCommentTBL>();
        }
    
        public int AnswerID { get; set; }
        public string Answer { get; set; }
        public int Score { get; set; }
        public System.DateTime AnswerDTS { get; set; }
        public int QuestionID { get; set; }
        public int UserID { get; set; }
        public bool Accepted { get; set; }
    
        public virtual ICollection<AnswerCommentTBL> AnswerCommentTBLs { get; set; }
        public virtual QuestionTBL QuestionTBL { get; set; }
        public virtual UserTBL UserTBL { get; set; }
    }
}
