//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxOverflow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryTBL
    {
        public CategoryTBL()
        {
            this.QuestionTBLs = new HashSet<QuestionTBL>();
        }
    
        public int CategoryID { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<QuestionTBL> QuestionTBLs { get; set; }
    }
}
