//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxOverflow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionVotingHistoryTBL
    {
        public int QVHID { get; set; }
        public int QVHUserID { get; set; }
        public int QVHQuestionID { get; set; }
        public System.DateTime QVHDTS { get; set; }
    }
}
