//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxOverflow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTBL
    {
        public QuestionTBL()
        {
            this.AnswerTBLs = new HashSet<AnswerTBL>();
            this.QuestionCommentTBLs = new HashSet<QuestionCommentTBL>();
        }
    
        public int QuestionID { get; set; }
        public string Question { get; set; }
        public int Score { get; set; }
        public System.DateTime QuestionDTS { get; set; }
        public int CategoryID { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<AnswerTBL> AnswerTBLs { get; set; }
        public virtual CategoryTBL CategoryTBL { get; set; }
        public virtual ICollection<QuestionCommentTBL> QuestionCommentTBLs { get; set; }
        public virtual UserTBL UserTBL { get; set; }
    }
}
