//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxOverflow.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TODBEntities : DbContext
    {
        public TODBEntities()
            : base("name=TODBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnswerCommentTBL> AnswerCommentTBLs { get; set; }
        public virtual DbSet<AnswerTBL> AnswerTBLs { get; set; }
        public virtual DbSet<AnswerVotingHistoryTBL> AnswerVotingHistoryTBLs { get; set; }
        public virtual DbSet<CategoryTBL> CategoryTBLs { get; set; }
        public virtual DbSet<QuestionCommentTBL> QuestionCommentTBLs { get; set; }
        public virtual DbSet<QuestionTBL> QuestionTBLs { get; set; }
        public virtual DbSet<QuestionVotingHistoryTBL> QuestionVotingHistoryTBLs { get; set; }
        public virtual DbSet<UserTBL> UserTBLs { get; set; }
    }
}
