//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTODB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerComment
    {
        public int ACommentID { get; set; }
        public string Comment { get; set; }
        public System.DateTime ACommentDTS { get; set; }
        public int AnswerID { get; set; }
        public int UserID { get; set; }
    
        public virtual Answers Answer { get; set; }
        public virtual UserInfo User { get; set; }
    }
}
