//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTODB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public Answers()
        {
            this.Score = 0;
            this.Answered = false;
            this.AnswerComments = new HashSet<AnswerComment>();
        }
    
        public int AnswerID { get; set; }
        public string Answer { get; set; }
        public int Score { get; set; }
        public System.DateTime AnswerDTS { get; set; }
        public bool Answered { get; set; }
        public int QuestionID { get; set; }
        public int UserID { get; set; }
    
        public virtual Questions Question { get; set; }
        public virtual ICollection<AnswerComment> AnswerComments { get; set; }
        public virtual UserInfo User { get; set; }
        public virtual AnswerVotingHistory AnswerVotingHistory { get; set; }
    }
}
