//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTODB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerVotingHistory
    {
        public int AVH_ID { get; set; }
    
        public virtual Answers Answer { get; set; }
        public virtual UserInfo User { get; set; }
    }
}
