//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTODB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.Score = 0;
            this.Answers = new HashSet<Answers>();
            this.QuestionComments = new HashSet<QuestionComment>();
        }
    
        public int QuestionID { get; set; }
        public string Question { get; set; }
        public int Score { get; set; }
        public System.DateTime QuestionDTS { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<Answers> Answers { get; set; }
        public virtual ICollection<QuestionComment> QuestionComments { get; set; }
        public virtual UserInfo User { get; set; }
        public virtual QuestionVotingHistory QuestionVotingHistory { get; set; }
        public virtual Categories Category { get; set; }
    }
}
