//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTODB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Questions = new HashSet<Questions>();
            this.Answers = new HashSet<Answers>();
            this.QuestionComments = new HashSet<QuestionComment>();
            this.AnswerComments = new HashSet<AnswerComment>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual ICollection<Answers> Answers { get; set; }
        public virtual ICollection<QuestionComment> QuestionComments { get; set; }
        public virtual ICollection<AnswerComment> AnswerComments { get; set; }
        public virtual AnswerVotingHistory AnswerVotingHistory { get; set; }
        public virtual QuestionVotingHistory QuestionVotingHistory { get; set; }
    }
}
