//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxOverflow2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers1
    {
        public Answers1()
        {
            this.AnswerComments = new HashSet<AnswerComment>();
            this.AnswerVotingHistories = new HashSet<AnswerVotingHistory>();
        }
    
        public int AnswerID { get; set; }
        public string Answer { get; set; }
        public int Score { get; set; }
        public System.DateTime AnswerDTS { get; set; }
        public bool Answered { get; set; }
        public int QuestionID { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<AnswerComment> AnswerComments { get; set; }
        public virtual ICollection<AnswerVotingHistory> AnswerVotingHistories { get; set; }
        public virtual Questions1 Questions1 { get; set; }
        public virtual User User { get; set; }
    }
}
