//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxOverflow2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerVotingHistory
    {
        public AnswerVotingHistory()
        {
            this.Users = new HashSet<User>();
        }
    
        public int AVH_ID { get; set; }
        public int Answer_AnswerID { get; set; }
    
        public virtual Answers1 Answers1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
