//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxOverflow2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions1
    {
        public Questions1()
        {
            this.Answers1 = new HashSet<Answers1>();
            this.QuestionComments = new HashSet<QuestionComment>();
            this.QuestionVotingHistories = new HashSet<QuestionVotingHistory>();
        }
    
        public int QuestionID { get; set; }
        public string Question { get; set; }
        public int Score { get; set; }
        public System.DateTime QuestionDTS { get; set; }
        public int UserID { get; set; }
        public int Category_CategoryID { get; set; }
    
        public virtual ICollection<Answers1> Answers1 { get; set; }
        public virtual Categories1 Categories1 { get; set; }
        public virtual ICollection<QuestionComment> QuestionComments { get; set; }
        public virtual ICollection<QuestionVotingHistory> QuestionVotingHistories { get; set; }
        public virtual User User { get; set; }
    }
}
