//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxOverflow2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionVotingHistory
    {
        public QuestionVotingHistory()
        {
            this.Users = new HashSet<User>();
        }
    
        public int QVH_ID { get; set; }
        public int Question_QuestionID { get; set; }
    
        public virtual Questions1 Questions1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
