//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxOverflow2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionCommentTBL
    {
        public int QCommentID { get; set; }
        public string QComment { get; set; }
        public System.DateTime QCommentDTS { get; set; }
        public int QuestionID { get; set; }
        public int UserID { get; set; }
    
        public virtual QuestionTBL QuestionTBL { get; set; }
        public virtual UserTBL UserTBL { get; set; }
    }
}
