//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxOverflow2013.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestTODBEntities : DbContext
    {
        public TestTODBEntities()
            : base("name=TestTODBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnswerComment> AnswerComments { get; set; }
        public virtual DbSet<Answers1> Answers1 { get; set; }
        public virtual DbSet<AnswerVotingHistory> AnswerVotingHistories { get; set; }
        public virtual DbSet<Categories1> Categories1 { get; set; }
        public virtual DbSet<QuestionComment> QuestionComments { get; set; }
        public virtual DbSet<Questions1> Questions1 { get; set; }
        public virtual DbSet<QuestionVotingHistory> QuestionVotingHistories { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
