//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxOverflow2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTBL
    {
        public UserTBL()
        {
            this.AnswerCommentTBLs = new HashSet<AnswerCommentTBL>();
            this.AnswerTBLs = new HashSet<AnswerTBL>();
            this.QuestionCommentTBLs = new HashSet<QuestionCommentTBL>();
            this.QuestionTBLs = new HashSet<QuestionTBL>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Reputation { get; set; }
    
        public virtual ICollection<AnswerCommentTBL> AnswerCommentTBLs { get; set; }
        public virtual ICollection<AnswerTBL> AnswerTBLs { get; set; }
        public virtual ICollection<QuestionCommentTBL> QuestionCommentTBLs { get; set; }
        public virtual ICollection<QuestionTBL> QuestionTBLs { get; set; }
    }
}
